import matplotlib.pyplot as plt
import numpy as np

filein = open("driven.txt")
Npoints = int(filein.readline())
tf = float(filein.readline())
dt = float(filein.readline())

t = np.arange(0,tf,dt)
psi = np.zeros(Npoints)
rho = np.zeros(Npoints)
exact = np.zeros(Npoints)
psi_c = np.zeros(Npoints)
rho_c = np.zeros(Npoints)
exact_c = np.zeros(Npoints)
Npsi = np.zeros(Npoints)
Np = np.zeros(Npoints)
Nm = np.zeros(Npoints)
Ng = np.zeros(Npoints)
Ne = np.zeros(Npoints)
gp = np.zeros(Npoints)
gm = np.zeros(Npoints)
b = np.zeros(Npoints)
psi_e = np.zeros(Npoints)
psi_g = np.zeros(Npoints)
g_p = np.zeros(Npoints)
g_m = np.zeros(Npoints)
e_p = np.zeros(Npoints)
e_m = np.zeros(Npoints)
p_g = np.zeros(Npoints)
p_e = np.zeros(Npoints)
m_g = np.zeros(Npoints)
m_e = np.zeros(Npoints)

for i in range(Npoints):
  line = filein.readline()
  rho[i] = float(line.split()[0])
  exact[i] = float(line.split()[1])
  psi[i] = float(line.split()[2])

  line = filein.readline()
  rho_c[i] = float(line.split()[0])
  exact_c[i] = float(line.split()[1])
  psi_c[i] = float(line.split()[2])

  line = filein.readline()
  Npsi[i] = float(line.split()[0])
  Ng[i] = float(line.split()[1])
  Ne[i] = float(line.split()[2])
  Np[i] = float(line.split()[3])
  Nm[i] = float(line.split()[4])

  line = filein.readline()
  gp[i] = float(line.split()[0])
  gm[i] = float(line.split()[1])
  b[i] = float(line.split()[2])

  line = filein.readline()
  psi_e[i] = float(line.split()[0])
  psi_g[i] = float(line.split()[1])
  g_p[i] = float(line.split()[2])
  g_m[i] = float(line.split()[3])
  e_p[i] = float(line.split()[4])
  e_m[i] = float(line.split()[5])
  p_g[i] = float(line.split()[6])
  p_e[i] = float(line.split()[7])
  m_g[i] = float(line.split()[8])
  m_e[i] = float(line.split()[9])

fig, ax = plt.subplots(2,2, figsize=(14,8), sharex = True)

ax[0,0].plot(t, rho, color = "red", label = r'$\rho$')
ax[0,0].plot(t, exact, color = "black", alpha = .7)
ax[0,0].plot(t ,psi, color = "green", label = r'$\psi$', alpha = .5)
ax[0,0].plot(t, rho_c, '--', color = "red", label = r'$\rho$')
ax[0,0].plot(t, exact_c, '--', color = "black", alpha = .7)
ax[0,0].plot(t ,psi_c, '--', color = "green", label = r'$\psi$', alpha = .5)
ax[0,0].set_ylabel(r'$tr[\rho\sigma_{z(x)}]$, solid(dashed)')
ax[0,0].legend(loc = "upper right")
ax[0,0].set_title(r'$z$ (solid) and $x$ (dashed) components')

ax[0,1].plot(t, Npsi, label = r'$\psi$')
ax[0,1].plot(t, Ng, label = r'$0$')
ax[0,1].plot(t, Ne, label = r'$1$')
ax[0,1].plot(t, Np, label = r'$+$')
ax[0,1].plot(t, Nm, label = r'$-$')
ax[0,1].set_ylabel(r'$N_i/N$')
ax[0,1].legend(loc = "upper right")
ax[0,1].set_title("Populations")

ax[1,0].plot(t, psi_e, label = r'$\psi \to 1$', marker = 'x', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, psi_g, label = r'$\psi \to 0$', marker = 'x', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, g_p, label = r'$0 \to +$', marker = 'o', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, g_m, label = r'$0 \to -$', marker = 'o', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, e_p, label = r'$1 \to +$', marker = 's', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, e_m, label = r'$1 \to -$', marker = 's', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, p_g, label = r'$+ \to 0$', marker = '^', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, p_e, label = r'$+ \to 1$', marker = '^', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, m_g, label = r'$- \to 0$', marker = 'D', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, m_e, label = r'$- \to 1$', marker = 'D', markevery = int(Npoints/30), markersize = 3, alpha = .8)
ax[1,0].plot(t, np.zeros(Npoints)+dt, alpha = .3, color = "black")
ax[1,0].legend(loc = "upper right")
ax[1,0].set_ylabel(r'$\lambda_{i \to j}dt$')
ax[1,0].set_title("Jump probabilities")
ax[1,0].set_xlabel(r'$t$')

ax[1,1].plot(t,gp, label = r'$\gamma_+$')
ax[1,1].plot(t,gm, label = r'$\gamma_-$')
ax[1,1].plot(t,b, label = r'$\beta$')
ax[1,1].set_xlabel(r'$t$')
ax[1,1].legend(loc = "lower right")
ax[1,1].set_title("Rates")

#plt.savefig("/Users/federico/Desktop/driven_"+str(np.random.default_rng().integers(0,10))+".png")
plt.show()